// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	addLibraryRoot: (path: string, label: string | null) => typedError<LibraryScan, AppError_Serialize>(__TAURI_INVOKE("add_library_root", { path, label })),
	getDesktopState: () => typedError<DesktopState, AppError_Serialize>(__TAURI_INVOKE("get_desktop_state")),
	getPlaybackState: () => typedError<PlaybackState, AppError_Serialize>(__TAURI_INVOKE("get_playback_state")),
	listLibraryRoots: () => typedError<LibraryRoot[], AppError_Serialize>(__TAURI_INVOKE("list_library_roots")),
	listAudioOutputDevices: () => typedError<AudioOutputDevice[], AppError_Serialize>(__TAURI_INVOKE("list_audio_output_devices")),
	pausePlayback: () => typedError<PlaybackState, AppError_Serialize>(__TAURI_INVOKE("pause_playback")),
	playTrack: (path: string) => typedError<PlaybackState, AppError_Serialize>(__TAURI_INVOKE("play_track", { path })),
	queryCatalogTracks: (query: CatalogQuery) => typedError<TrackPage, AppError_Serialize>(__TAURI_INVOKE("query_catalog_tracks", { query })),
	removeLibraryRoot: (rootId: string, confirmed: boolean) => typedError<null, AppError_Serialize>(__TAURI_INVOKE("remove_library_root", { rootId, confirmed })),
	rescanLibraryRoot: (rootId: string) => typedError<LibraryScan, AppError_Serialize>(__TAURI_INVOKE("rescan_library_root", { rootId })),
	resumePlayback: () => typedError<PlaybackState, AppError_Serialize>(__TAURI_INVOKE("resume_playback")),
	restoreLibraryRoot: (rootId: string) => typedError<LibraryScan, AppError_Serialize>(__TAURI_INVOKE("restore_library_root", { rootId })),
	scanLibrary: (root: string) => typedError<LibraryScan, AppError_Serialize>(__TAURI_INVOKE("scan_library", { root })),
	selectAudioOutputDevice: (deviceId: string | null) => typedError<AudioOutputDevice[], AppError_Serialize>(__TAURI_INVOKE("select_audio_output_device", { deviceId })),
	seekPlayback: (positionMs: number) => typedError<PlaybackState, AppError_Serialize>(__TAURI_INVOKE("seek_playback", { positionMs })),
	setHifiMode: (enabled: boolean) => typedError<PlaybackState, AppError_Serialize>(__TAURI_INVOKE("set_hifi_mode", { enabled })),
	setLibraryRootEnabled: (rootId: string, enabled: boolean) => typedError<LibraryRoot, AppError_Serialize>(__TAURI_INVOKE("set_library_root_enabled", { rootId, enabled })),
	setVolume: (volume: number | null) => typedError<PlaybackState, AppError_Serialize>(__TAURI_INVOKE("set_volume", { volume })),
	stopPlayback: () => typedError<PlaybackState, AppError_Serialize>(__TAURI_INVOKE("stop_playback")),
};

/* Types */
export type AppError = AppError_Serialize | AppError_Deserialize;

export type AppError_Deserialize = {
	code: string,
	message: string,
	context: { [key in string]: string } | null,
};

export type AppError_Serialize = {
	code: string,
	message: string,
	context?: { [key in string]: string } | null,
};

export type ArtistReference = {
	id: string,
	name: string,
};

export type AudioExtension = "flac" | "wav" | "mp3" | "ogg" | "aac" | "aiff" | "m4a";

export type AudioOutputDevice = {
	id: string,
	name: string,
	isDefault: boolean,
	isSelected: boolean,
};

export type AudioOutputState = {
	deviceId: string,
	deviceName: string,
	sourceSampleRate: number,
	sourceChannels: number,
	sourceBitDepth: number | null,
	outputSampleRate: number,
	outputChannels: number,
	outputSampleFormat: string,
	nativeSampleRate: boolean,
	resampling: boolean,
	softwareGain: boolean,
	exclusiveMode: boolean,
	bitPerfect: boolean,
	disclosure: string,
};

export type CatalogQuery = {
	rootId: string | null,
	search: string | null,
	available: boolean | null,
	sort: TrackSort,
	direction: SortDirection,
	offset: number,
	limit: number,
};

export type DesktopState = {
	libraryRoot: string | null,
	libraryRoots: LibraryRoot[],
	playback: PlaybackState,
};

export type LibraryChanged = {
	kind: string,
	rootId: string | null,
	trackIds: string[],
};

export type LibraryRoot = {
	id: string,
	path: string,
	label: string,
	enabled: boolean,
	availability: RootAvailability,
	watchMode: WatchMode,
	trackCount: number,
	lastScanAt: string | null,
};

export type LibraryScan = {
	rootId: string,
	root: string,
	tracks: TrackSummary[],
	warnings: string[],
};

export type PlaybackState = {
	trackId: string | null,
	path: string | null,
	status: PlaybackStatus,
	positionMs: number,
	durationMs: number,
	volume: number | null,
	muted: boolean,
	hifiMode: boolean,
	output: AudioOutputState | null,
};

export type PlaybackStatus = "stopped" | "loading" | "playing" | "paused" | "ended" | "error";

export type RootAvailability = "online" | "offline" | "permission-error";

export type ScanProgress = {
	scannedFiles: number,
	discoveredTracks: number,
	currentPath: string | null,
};

export type SortDirection = "ascending" | "descending";

export type TrackPage = {
	items: TrackSummary[],
	total: number,
	offset: number,
	limit: number,
};

export type TrackSort = "title" | "path" | "date-added" | "last-modified";

export type TrackSummary = {
	id: string,
	rootId: string,
	path: string,
	relativePath: string,
	title: string,
	sortTitle: string | null,
	artists: ArtistReference[],
	albumArtists: ArtistReference[],
	albumId: string | null,
	album: string,
	genres: string[],
	trackNumber: number | null,
	trackTotal: number | null,
	discNumber: number | null,
	discTotal: number | null,
	year: number | null,
	date: string | null,
	composer: string | null,
	label: string | null,
	catalogNumber: string | null,
	isrc: string | null,
	musicbrainzRecordingId: string | null,
	artworkId: string | null,
	extension: AudioExtension,
	fileSize: number,
	durationMs: number | null,
	sampleRate: number | null,
	channels: number | null,
	bitDepth: number | null,
	available: boolean,
};

export type WatchMode = "native" | "poll" | "manual";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

