// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	addLibraryRoot: (path: string, label: string | null) => typedError<LibraryScan, AppError_Serialize>(__TAURI_INVOKE("add_library_root", { path, label })),
	applyMusicbrainzCandidate: (trackId: string, candidate: EnrichmentCandidate) => typedError<MetadataPatch, AppError_Serialize>(__TAURI_INVOKE("apply_musicbrainz_candidate", { trackId, candidate })),
	cleanupMissingTracks: (rootId: string | null, confirmed: boolean) => typedError<number, AppError_Serialize>(__TAURI_INVOKE("cleanup_missing_tracks", { rootId, confirmed })),
	getAlbumDetail: (albumId: string) => typedError<AlbumDetail, AppError_Serialize>(__TAURI_INVOKE("get_album_detail", { albumId })),
	getArtistDetail: (artistId: string) => typedError<ArtistDetail, AppError_Serialize>(__TAURI_INVOKE("get_artist_detail", { artistId })),
	getDesktopState: () => typedError<DesktopState, AppError_Serialize>(__TAURI_INVOKE("get_desktop_state")),
	getMetadataDraft: (trackId: string) => typedError<{
	title: string | null,
	artists: string[] | null,
	album: string | null,
	albumArtists: string[] | null,
	genres: string[] | null,
	trackNumber: number | null,
	trackTotal: number | null,
	discNumber: number | null,
	discTotal: number | null,
	year: number | null,
	date: string | null,
	composer: string | null,
	label: string | null,
	catalogNumber: string | null,
	isrc: string | null,
	artworkId: string | null,
} | null, AppError_Serialize>(__TAURI_INVOKE("get_metadata_draft", { trackId })),
	getMusicbrainzEnabled: () => __TAURI_INVOKE<boolean>("get_musicbrainz_enabled"),
	getPlaybackState: () => typedError<PlaybackState, AppError_Serialize>(__TAURI_INVOKE("get_playback_state")),
	getTrackMetadata: (trackId: string) => typedError<TrackSummary, AppError_Serialize>(__TAURI_INVOKE("get_track_metadata", { trackId })),
	listLibraryRoots: () => typedError<LibraryRoot[], AppError_Serialize>(__TAURI_INVOKE("list_library_roots")),
	listAudioOutputDevices: () => typedError<AudioOutputDevice[], AppError_Serialize>(__TAURI_INVOKE("list_audio_output_devices")),
	pausePlayback: () => typedError<PlaybackState, AppError_Serialize>(__TAURI_INVOKE("pause_playback")),
	playTrack: (path: string) => typedError<PlaybackState, AppError_Serialize>(__TAURI_INVOKE("play_track", { path })),
	queryCatalogTracks: (query: CatalogQuery) => typedError<TrackPage, AppError_Serialize>(__TAURI_INVOKE("query_catalog_tracks", { query })),
	queryDiscovery: (query: DiscoveryQuery) => typedError<DiscoveryCatalog, AppError_Serialize>(__TAURI_INVOKE("query_discovery", { query })),
	removeLibraryRoot: (rootId: string, confirmed: boolean) => typedError<null, AppError_Serialize>(__TAURI_INVOKE("remove_library_root", { rootId, confirmed })),
	rescanLibraryRoot: (rootId: string) => typedError<LibraryScan, AppError_Serialize>(__TAURI_INVOKE("rescan_library_root", { rootId })),
	resumePlayback: () => typedError<PlaybackState, AppError_Serialize>(__TAURI_INVOKE("resume_playback")),
	restoreLibraryRoot: (rootId: string) => typedError<LibraryScan, AppError_Serialize>(__TAURI_INVOKE("restore_library_root", { rootId })),
	rollbackMetadataFile: (trackId: string) => typedError<MetadataWriteResult, AppError_Serialize>(__TAURI_INVOKE("rollback_metadata_file", { trackId })),
	runMusicbrainzEnrichment: (trackId: string) => typedError<EnrichmentJob, AppError_Serialize>(__TAURI_INVOKE("run_musicbrainz_enrichment", { trackId })),
	saveMetadataDraft: (trackId: string, patch: MetadataPatch) => typedError<MetadataPatch, AppError_Serialize>(__TAURI_INVOKE("save_metadata_draft", { trackId, patch })),
	saveMetadataDrafts: (trackIds: string[], patch: MetadataPatch) => typedError<number, AppError_Serialize>(__TAURI_INVOKE("save_metadata_drafts", { trackIds, patch })),
	scanLibrary: (root: string) => typedError<LibraryScan, AppError_Serialize>(__TAURI_INVOKE("scan_library", { root })),
	selectAudioOutputDevice: (deviceId: string | null) => typedError<AudioOutputDevice[], AppError_Serialize>(__TAURI_INVOKE("select_audio_output_device", { deviceId })),
	seekPlayback: (positionMs: number) => typedError<PlaybackState, AppError_Serialize>(__TAURI_INVOKE("seek_playback", { positionMs })),
	setHifiMode: (enabled: boolean) => typedError<PlaybackState, AppError_Serialize>(__TAURI_INVOKE("set_hifi_mode", { enabled })),
	setLibraryRootEnabled: (rootId: string, enabled: boolean) => typedError<LibraryRoot, AppError_Serialize>(__TAURI_INVOKE("set_library_root_enabled", { rootId, enabled })),
	setMusicbrainzEnabled: (enabled: boolean) => __TAURI_INVOKE<boolean>("set_musicbrainz_enabled", { enabled }),
	setVolume: (volume: number | null) => typedError<PlaybackState, AppError_Serialize>(__TAURI_INVOKE("set_volume", { volume })),
	stopPlayback: () => typedError<PlaybackState, AppError_Serialize>(__TAURI_INVOKE("stop_playback")),
	writeMetadataToFile: (trackId: string) => typedError<MetadataWriteResult, AppError_Serialize>(__TAURI_INVOKE("write_metadata_to_file", { trackId })),
};

/* Types */
export type AlbumDetail = {
	album: AlbumSummary,
	tracks: TrackSummary[],
};

export type AlbumSummary = {
	id: string,
	title: string,
	artists: ArtistReference[],
	year: number | null,
	label: string | null,
	catalogNumber: string | null,
	artworkId: string | null,
	trackCount: number,
	totalDurationMs: number,
};

export type AppError = AppError_Serialize | AppError_Deserialize;

export type AppError_Deserialize = {
	code: string,
	message: string,
	context: { [key in string]: string } | null,
};

export type AppError_Serialize = {
	code: string,
	message: string,
	context?: { [key in string]: string } | null,
};

export type ArtistDetail = {
	artist: ArtistSummary,
	albums: AlbumSummary[],
	tracks: TrackSummary[],
};

export type ArtistReference = {
	id: string,
	name: string,
};

export type ArtistSummary = {
	id: string,
	name: string,
	genres: string[],
	albumCount: number,
	trackCount: number,
	totalDurationMs: number,
	artworkId: string | null,
};

export type AudioExtension = "flac" | "wav" | "mp3" | "ogg" | "aac" | "aiff" | "m4a";

export type AudioOutputDevice = {
	id: string,
	name: string,
	isDefault: boolean,
	isSelected: boolean,
};

export type AudioOutputState = {
	deviceId: string,
	deviceName: string,
	sourceSampleRate: number,
	sourceChannels: number,
	sourceBitDepth: number | null,
	outputSampleRate: number,
	outputChannels: number,
	outputSampleFormat: string,
	nativeSampleRate: boolean,
	resampling: boolean,
	softwareGain: boolean,
	exclusiveMode: boolean,
	bitPerfect: boolean,
	disclosure: string,
};

export type CatalogQuery = {
	rootId: string | null,
	search: string | null,
	available: boolean | null,
	sort: TrackSort,
	direction: SortDirection,
	offset: number,
	limit: number,
};

export type DesktopState = {
	libraryRoot: string | null,
	libraryRoots: LibraryRoot[],
	playback: PlaybackState,
};

export type DiscoveryCatalog = {
	artists: ArtistSummary[],
	albums: AlbumSummary[],
	genres: GenreSummary[],
};

export type DiscoveryQuery = {
	search: string | null,
	offset: number,
	limit: number,
};

export type EnrichmentCandidate = {
	recordingId: string,
	title: string,
	artists: string[],
	releaseId: string | null,
	release: string | null,
	albumArtists: string[],
	trackNumber: number | null,
	trackTotal: number | null,
	durationMs: number | null,
	score: number,
	requiresReview: boolean,
};

export type EnrichmentJob = {
	trackId: string,
	status: string,
	candidates: EnrichmentCandidate[],
	autoApplied: boolean,
	fromCache: boolean,
};

export type GenreSummary = {
	id: string,
	name: string,
	albumCount: number,
	trackCount: number,
	artists: ArtistReference[],
};

export type LibraryChanged = {
	kind: string,
	rootId: string | null,
	trackIds: string[],
};

export type LibraryRoot = {
	id: string,
	path: string,
	label: string,
	enabled: boolean,
	availability: RootAvailability,
	watchMode: WatchMode,
	trackCount: number,
	lastScanAt: string | null,
};

export type LibraryScan = {
	rootId: string,
	root: string,
	tracks: TrackSummary[],
	warnings: string[],
};

export type MetadataPatch = {
	title: string | null,
	artists: string[] | null,
	album: string | null,
	albumArtists: string[] | null,
	genres: string[] | null,
	trackNumber: number | null,
	trackTotal: number | null,
	discNumber: number | null,
	discTotal: number | null,
	year: number | null,
	date: string | null,
	composer: string | null,
	label: string | null,
	catalogNumber: string | null,
	isrc: string | null,
	artworkId: string | null,
};

export type MetadataWriteResult = {
	trackId: string,
	path: string,
	backupPath: string,
};

export type PlaybackState = {
	trackId: string | null,
	path: string | null,
	status: PlaybackStatus,
	positionMs: number,
	durationMs: number,
	volume: number | null,
	muted: boolean,
	hifiMode: boolean,
	output: AudioOutputState | null,
};

export type PlaybackStatus = "stopped" | "loading" | "playing" | "paused" | "ended" | "error";

export type RootAvailability = "online" | "offline" | "permission-error";

export type ScanProgress = {
	scannedFiles: number,
	discoveredTracks: number,
	currentPath: string | null,
};

export type SortDirection = "ascending" | "descending";

export type TrackPage = {
	items: TrackSummary[],
	total: number,
	offset: number,
	limit: number,
};

export type TrackSort = "title" | "path" | "date-added" | "last-modified";

export type TrackSummary = {
	id: string,
	rootId: string,
	path: string,
	relativePath: string,
	title: string,
	sortTitle: string | null,
	artists: ArtistReference[],
	albumArtists: ArtistReference[],
	albumId: string | null,
	album: string,
	genres: string[],
	trackNumber: number | null,
	trackTotal: number | null,
	discNumber: number | null,
	discTotal: number | null,
	year: number | null,
	date: string | null,
	composer: string | null,
	label: string | null,
	catalogNumber: string | null,
	isrc: string | null,
	musicbrainzRecordingId: string | null,
	artworkId: string | null,
	extension: AudioExtension,
	fileSize: number,
	durationMs: number | null,
	sampleRate: number | null,
	channels: number | null,
	bitDepth: number | null,
	available: boolean,
};

export type WatchMode = "native" | "poll" | "manual";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

