import { TrackItem, AlbumItem, ArtistItem } from '../types';
import { isDemoMode } from './mode';

export const DEMO_TRACKS: TrackItem[] = [
  {
    id: 't-1',
    trackNumber: 1,
    title: 'Welcome to the Machine',
    artist: 'Pink Floyd',
    album: 'Wish You Were Here',
    codec: 'FLAC',
    sampleRate: '24-bit/192kHz',
    dynamicRange: 'DR15',
    bitrate: '4608 kbps',
    replayGain: '-1.8dB',
    year: 1975,
    catalogNumber: 'PC-33453',
    duration: '7:27',
    durationSeconds: 447,
    coverUrl:
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 't-2',
    trackNumber: 2,
    title: 'Shine On You Crazy Diamond (Pts. 1-5)',
    artist: 'Pink Floyd',
    album: 'Wish You Were Here',
    codec: 'FLAC',
    sampleRate: '24-bit/192kHz',
    dynamicRange: 'DR15',
    bitrate: '4608 kbps',
    replayGain: '-1.8dB',
    year: 1975,
    catalogNumber: 'PC-33452',
    duration: '13:30',
    durationSeconds: 810,
    coverUrl:
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 't-3',
    trackNumber: 3,
    title: 'Have a Cigar',
    artist: 'Pink Floyd',
    album: 'Wish You Were Here',
    codec: 'FLAC',
    sampleRate: '24-bit/192kHz',
    dynamicRange: 'DR13',
    bitrate: '4608 kbps',
    replayGain: '-1.8dB',
    year: 1975,
    catalogNumber: 'PC-33452',
    duration: '5:08',
    durationSeconds: 308,
    coverUrl:
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 't-4',
    trackNumber: 4,
    title: 'Wish You Were Here',
    artist: 'Pink Floyd',
    album: 'Wish You Were Here',
    codec: 'FLAC',
    sampleRate: '24-bit/192kHz',
    dynamicRange: 'DR14',
    bitrate: '4608 kbps',
    replayGain: '-1.3dB',
    year: 1975,
    catalogNumber: 'PC-33470',
    duration: '5:34',
    durationSeconds: 334,
    coverUrl:
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 't-5',
    trackNumber: 5,
    title: 'Shine On You Crazy Diamond (Pts. 6-9)',
    artist: 'Pink Floyd',
    album: 'Wish You Were Here',
    codec: 'FLAC',
    sampleRate: '24-bit/192kHz',
    dynamicRange: 'DR14',
    bitrate: '4608 kbps',
    replayGain: '-1.8dB',
    year: 1975,
    catalogNumber: 'PC-33473',
    duration: '12:28',
    durationSeconds: 748,
    coverUrl:
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 't-6',
    trackNumber: 6,
    title: 'Time',
    artist: 'Pink Floyd',
    album: 'The Dark Side of the Moon',
    codec: 'FLAC',
    sampleRate: '24-bit/192kHz',
    dynamicRange: 'DR13',
    bitrate: '4608 kbps',
    replayGain: '-1.9dB',
    year: 1973,
    catalogNumber: 'PC-33453',
    duration: '7:06',
    durationSeconds: 426,
    coverUrl:
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 't-7',
    trackNumber: 7,
    title: 'Money',
    artist: 'Pink Floyd',
    album: 'The Dark Side of the Moon',
    codec: 'FLAC',
    sampleRate: '24-bit/192kHz',
    dynamicRange: 'DR13',
    bitrate: '4608 kbps',
    replayGain: '-1.0dB',
    year: 1973,
    catalogNumber: 'PC-33461',
    duration: '6:22',
    durationSeconds: 382,
    coverUrl:
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 't-8',
    trackNumber: 8,
    title: 'Black Dog',
    artist: 'Led Zeppelin',
    album: 'Led Zeppelin IV',
    codec: 'FLAC',
    sampleRate: '24/96',
    dynamicRange: 'DR14',
    bitrate: '4308 kbps',
    replayGain: '-1.8dB',
    year: 1971,
    catalogNumber: 'PC-33452',
    duration: '4:56',
    durationSeconds: 296,
    coverUrl:
      'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 't-9',
    trackNumber: 9,
    title: 'Rock and Roll',
    artist: 'Led Zeppelin',
    album: 'Led Zeppelin IV',
    codec: 'FLAC',
    sampleRate: '24/96',
    dynamicRange: 'DR15',
    bitrate: '2906 kbps',
    replayGain: '-1.8dB',
    year: 1971,
    catalogNumber: '-',
    duration: '3:40',
    durationSeconds: 220,
    coverUrl:
      'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 't-10',
    trackNumber: 10,
    title: 'Stairway to Heaven',
    artist: 'Led Zeppelin',
    album: 'Led Zeppelin IV',
    codec: 'FLAC',
    sampleRate: '24/96',
    dynamicRange: 'DR12',
    bitrate: '4009 kbps',
    replayGain: '-1.0dB',
    year: 1971,
    catalogNumber: 'PC-33457',
    duration: '8:02',
    durationSeconds: 482,
    coverUrl:
      'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 't-11',
    trackNumber: 11,
    title: "Since I've Been Loving You",
    artist: 'Led Zeppelin',
    album: 'Led Zeppelin III',
    codec: 'FLAC',
    sampleRate: '24/96',
    dynamicRange: 'DR13',
    bitrate: '3075 kbps',
    replayGain: '-1.2dB',
    year: 1970,
    catalogNumber: 'PC-33450',
    duration: '7:24',
    durationSeconds: 444,
    coverUrl:
      'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 't-12',
    trackNumber: 12,
    title: 'Immigrant Song',
    artist: 'Led Zeppelin',
    album: 'Led Zeppelin III',
    codec: 'FLAC',
    sampleRate: '24/96',
    dynamicRange: 'DR12',
    bitrate: '3079 kbps',
    replayGain: '-2.2dB',
    year: 1970,
    catalogNumber: 'PC-33454',
    duration: '2:26',
    durationSeconds: 146,
    coverUrl:
      'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 't-13',
    trackNumber: 13,
    title: 'Tank!',
    artist: 'The Seatbelts',
    album: 'Cowboy Bebop (OST 1)',
    codec: 'FLAC',
    sampleRate: '24-bit/192kHz',
    dynamicRange: 'DR15',
    bitrate: '4016 kbps',
    replayGain: '-1.8dB',
    year: 1998,
    catalogNumber: 'PC-33452',
    duration: '3:30',
    durationSeconds: 210,
    coverUrl:
      'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 't-14',
    trackNumber: 14,
    title: 'Rush',
    artist: 'The Seatbelts',
    album: 'Cowboy Bebop (OST 1)',
    codec: 'FLAC',
    sampleRate: '24-bit/192kHz',
    dynamicRange: 'DR15',
    bitrate: '3078 kbps',
    replayGain: '-4.6dB',
    year: 1998,
    catalogNumber: 'PC-33452',
    duration: '3:34',
    durationSeconds: 214,
    coverUrl:
      'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 't-15',
    trackNumber: 15,
    title: 'Space Lion',
    artist: 'The Seatbelts',
    album: 'Cowboy Bebop (OST 1)',
    codec: 'FLAC',
    sampleRate: '24-bit/192kHz',
    dynamicRange: 'DR15',
    bitrate: '3088 kbps',
    replayGain: '-1.0dB',
    year: 1998,
    catalogNumber: 'PC-33452',
    duration: '7:11',
    durationSeconds: 431,
    coverUrl:
      'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 't-16',
    trackNumber: 16,
    title: 'So What',
    artist: 'Miles Davis',
    album: 'Kind of Blue',
    codec: 'DSD64',
    sampleRate: 'DSD256',
    dynamicRange: 'DR15',
    bitrate: '5644 kbps',
    replayGain: '-4.6dB',
    year: 1959,
    catalogNumber: 'PC-33452',
    duration: '9:22',
    durationSeconds: 562,
    coverUrl:
      'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=80',
  },
  {
    id: 't-17',
    trackNumber: 17,
    title: 'Freddie Freeloader',
    artist: 'Miles Davis',
    album: 'Kind of Blue',
    codec: 'DSD64',
    sampleRate: 'DSD256',
    dynamicRange: 'DR13',
    bitrate: '2368 kbps',
    replayGain: '-1.9dB',
    year: 1959,
    catalogNumber: 'PC-33453',
    duration: '9:49',
    durationSeconds: 589,
    coverUrl:
      'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=80',
  },
];

export const DEMO_ARTISTS: ArtistItem[] = [
  {
    id: 'art-3',
    name: 'The Seatbelts',
    displayName: 'The Seatbelts / Yoko Kanno',
    genres: ['Big Band Jazz', 'Blues', 'Bebop'],
    albumCount: 12,
    trackCount: 142,
    totalDuration: '11h 45m',
    avatarUrl:
      'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    bannerUrl:
      'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=1600&auto=format&fit=crop&q=80',
    featuredCoverUrl:
      'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
    bioSummary:
      'Formed to create the genre-bending soundtrack for Cowboy Bebop, this collective led by Yoko Kanno masterfully blends high-energy jazz, blues, rock, and electronic elements.',
    losslessPlaytime: '142h Lossless',
    losslessPercentage: '100%',
    localStorageSize: '8.4 GB',
    discography: [
      {
        id: 'cb-1',
        title: 'Cowboy Bebop OST 1',
        year: 1998,
        formatBadge: 'DSD64',
        coverUrl:
          'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
        trackCount: 22,
        isLocal: true,
        fileSize: '1.82 GB',
        releaseType: 'Soundtrack',
        catalogNumber: 'VICL-60201',
      },
      {
        id: 'cb-7',
        title: 'Ask DNA',
        year: 2001,
        formatBadge: 'FLAC 24/96',
        coverUrl:
          'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=80',
        trackCount: 5,
        isLocal: true,
        fileSize: '420 MB',
        releaseType: 'EP',
        catalogNumber: 'VICL-60756',
      },
      {
        id: 'cb-2',
        title: 'No Disc',
        year: 1998,
        formatBadge: 'FLAC 24/192',
        isNoDisc: true,
        trackCount: 18,
        isLocal: false,
        fileSize: '1.45 GB',
        releaseType: 'Soundtrack',
        catalogNumber: 'VICL-60202',
      },
      {
        id: 'cb-3',
        title: 'Blue',
        year: 1999,
        formatBadge: 'DSD64',
        coverUrl:
          'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
        trackCount: 17,
        isLocal: false,
        fileSize: '1.68 GB',
        releaseType: 'Soundtrack',
        catalogNumber: 'VICL-60203',
      },
      {
        id: 'cb-4',
        title: 'Vitaminless',
        year: 1998,
        formatBadge: 'FLAC 24/192',
        coverUrl:
          'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&auto=format&fit=crop&q=80',
        trackCount: 8,
        isLocal: false,
        fileSize: '680 MB',
        releaseType: 'EP',
        catalogNumber: 'VICL-60204',
      },
      {
        id: 'cb-6',
        title: 'Cowboy Bebop Remixes: Music for Freelance',
        year: 1999,
        formatBadge: 'FLAC 24/96',
        coverUrl:
          'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
        trackCount: 15,
        isLocal: false,
        fileSize: '950 MB',
        releaseType: 'Remixes',
        catalogNumber: 'VICL-60375',
      },
      {
        id: 'cb-8',
        title: 'Future Blues',
        year: 2001,
        formatBadge: 'FLAC 24/192',
        coverUrl:
          'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=600&auto=format&fit=crop&q=80',
        trackCount: 18,
        isLocal: false,
        fileSize: '1.92 GB',
        releaseType: 'Soundtrack',
        catalogNumber: 'VICL-60757',
      },
      {
        id: 'cb-10',
        title: 'Tank! THE! BEST!',
        year: 2004,
        formatBadge: 'FLAC 24/192',
        coverUrl:
          'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
        trackCount: 20,
        isLocal: false,
        fileSize: '2.10 GB',
        releaseType: 'Compilation',
        catalogNumber: 'VICL-61543',
      },
    ],
    topTracks: [
      {
        id: 'st-1',
        rank: 1,
        title: 'Tank!',
        artist: 'The Seatbelts',
        album: 'Cowboy Bebop OST 1',
        dynamicRange: 'DR14',
        format: '24-bit/96kHz',
        playCount: 39,
        isFavorite: true,
        duration: '3:30',
        durationSeconds: 210,
      },
      {
        id: 'st-2',
        rank: 2,
        title: 'Rush',
        artist: 'The Seatbelts',
        album: 'Cowboy Bebop OST 1',
        dynamicRange: 'DR14',
        format: '24-bit/96kHz',
        playCount: 23,
        isFavorite: true,
        duration: '3:34',
        durationSeconds: 214,
      },
      {
        id: 'st-3',
        rank: 3,
        title: 'Spokey Dokey',
        artist: 'The Seatbelts',
        album: 'Cowboy Bebop OST 1',
        dynamicRange: 'DR14',
        format: '24-bit/96kHz',
        playCount: 27,
        isFavorite: true,
        duration: '4:04',
        durationSeconds: 244,
      },
      {
        id: 'st-4',
        rank: 4,
        title: 'Too Good Too Bad',
        artist: 'The Seatbelts',
        album: 'Cowboy Bebop OST 1',
        dynamicRange: 'DR14',
        format: '24-bit/96kHz',
        playCount: 4,
        isFavorite: true,
        duration: '2:34',
        durationSeconds: 154,
      },
      {
        id: 'st-5',
        rank: 5,
        title: 'Space Lion',
        artist: 'The Seatbelts',
        album: 'Cowboy Bebop OST 1',
        dynamicRange: 'DR14',
        format: '24-bit/96kHz',
        playCount: 11,
        isFavorite: false,
        duration: '7:11',
        durationSeconds: 431,
      },
      {
        id: 'st-6',
        rank: 6,
        title: 'Real Folk Blues',
        artist: 'The Seatbelts',
        album: 'Cowboy Bebop OST 1',
        dynamicRange: 'DR14',
        format: '24-bit/96kHz',
        playCount: 3,
        isFavorite: false,
        duration: '6:17',
        durationSeconds: 377,
      },
      {
        id: 'st-7',
        rank: 7,
        title: 'Bad Dog No Biscuit',
        artist: 'The Seatbelts',
        album: 'Cowboy Bebop OST 1',
        dynamicRange: 'DR14',
        format: '24-bit/96kHz',
        playCount: 13,
        isFavorite: true,
        duration: '4:15',
        durationSeconds: 255,
      },
      {
        id: 'st-8',
        rank: 8,
        title: 'Call Me Call Me',
        artist: 'The Seatbelts',
        album: 'Blue',
        dynamicRange: 'DR14',
        format: '24-bit/96kHz',
        playCount: 17,
        isFavorite: true,
        duration: '4:42',
        durationSeconds: 282,
      },
      {
        id: 'st-9',
        rank: 9,
        title: 'Blue',
        artist: 'The Seatbelts',
        album: 'Blue',
        dynamicRange: 'DR14',
        format: '24-bit/96kHz',
        playCount: 6,
        isFavorite: false,
        duration: '5:04',
        durationSeconds: 304,
      },
      {
        id: 'st-10',
        rank: 10,
        title: 'Gotta Knock a Little Harder',
        artist: 'The Seatbelts',
        album: 'Future Blues',
        dynamicRange: 'DR14',
        format: '24-bit/96kHz',
        playCount: 2,
        isFavorite: true,
        duration: '5:24',
        durationSeconds: 324,
      },
      {
        id: 'st-11',
        rank: 11,
        title: 'The Egg and I',
        artist: 'The Seatbelts',
        album: 'Vitaminless',
        dynamicRange: 'DR14',
        format: '24-bit/96kHz',
        playCount: 3,
        isFavorite: false,
        duration: '2:42',
        durationSeconds: 162,
      },
      {
        id: 'st-12',
        rank: 12,
        title: 'Rain',
        artist: 'The Seatbelts',
        album: 'Cowboy Bebop OST 1',
        dynamicRange: 'DR14',
        format: '24-bit/96kHz',
        playCount: 2,
        isFavorite: true,
        duration: '3:23',
        durationSeconds: 203,
      },
    ],
  },
  {
    id: 'art-1',
    name: 'Pink Floyd',
    displayName: 'Pink Floyd',
    genres: ['Progressive Rock', 'Psychedelic Rock', 'Art Rock'],
    albumCount: 15,
    trackCount: 165,
    totalDuration: '14h 22m',
    avatarUrl:
      'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=600&auto=format&fit=crop&q=80',
    bannerUrl:
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1600&auto=format&fit=crop&q=80',
    featuredCoverUrl:
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
    bioSummary:
      'Pioneering English rock band formed in London in 1965, distinguished by their extended compositions, sonic experimentation, philosophical lyrics, and elaborate live shows.',
    losslessPlaytime: '64h Lossless',
    losslessPercentage: '100%',
    localStorageSize: '12.2 GB',
    discography: [
      {
        id: 'pf-1',
        title: 'Wish You Were Here',
        year: 1975,
        formatBadge: 'FLAC 24/192',
        coverUrl:
          'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
        trackCount: 5,
        isLocal: true,
        fileSize: '1.45 GB',
        releaseType: 'Studio Album',
        catalogNumber: 'PC-33453',
      },
      {
        id: 'pf-2',
        title: 'The Dark Side of the Moon',
        year: 1973,
        formatBadge: 'FLAC 24/192',
        coverUrl:
          'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
        trackCount: 10,
        isLocal: true,
        fileSize: '1.38 GB',
        releaseType: 'Studio Album',
        catalogNumber: 'SHVL-804',
      },
      {
        id: 'pf-3',
        title: 'Animals',
        year: 1977,
        formatBadge: 'FLAC 24/96',
        coverUrl:
          'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&auto=format&fit=crop&q=80',
        trackCount: 5,
        isLocal: false,
        fileSize: '1.10 GB',
        releaseType: 'Studio Album',
        catalogNumber: 'JC-34474',
      },
      {
        id: 'pf-4',
        title: 'The Wall',
        year: 1979,
        formatBadge: 'FLAC 24/96',
        coverUrl:
          'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
        trackCount: 26,
        isLocal: false,
        fileSize: '2.40 GB',
        releaseType: 'Studio Album',
        catalogNumber: 'PC2-36183',
      },
      {
        id: 'pf-5',
        title: 'Meddle',
        year: 1971,
        formatBadge: 'FLAC 24/96',
        coverUrl:
          'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=80',
        trackCount: 6,
        isLocal: false,
        fileSize: '890 MB',
        releaseType: 'Studio Album',
        catalogNumber: 'SHVL-795',
      },
      {
        id: 'pf-6',
        title: 'The Division Bell',
        year: 1994,
        formatBadge: 'FLAC 24/96',
        coverUrl:
          'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=600&auto=format&fit=crop&q=80',
        trackCount: 11,
        isLocal: false,
        fileSize: '1.25 GB',
        releaseType: 'Studio Album',
        catalogNumber: 'C-64200',
      },
    ],
    topTracks: [
      {
        id: 'pft-1',
        rank: 1,
        title: 'Welcome to the Machine',
        artist: 'Pink Floyd',
        album: 'Wish You Were Here',
        dynamicRange: 'DR15',
        format: '24-bit/192kHz',
        playCount: 48,
        isFavorite: true,
        duration: '7:27',
        durationSeconds: 447,
      },
      {
        id: 'pft-2',
        rank: 2,
        title: 'Time',
        artist: 'Pink Floyd',
        album: 'The Dark Side of the Moon',
        dynamicRange: 'DR13',
        format: '24-bit/192kHz',
        playCount: 36,
        isFavorite: true,
        duration: '7:06',
        durationSeconds: 426,
      },
      {
        id: 'pft-3',
        rank: 3,
        title: 'Shine On You Crazy Diamond',
        artist: 'Pink Floyd',
        album: 'Wish You Were Here',
        dynamicRange: 'DR15',
        format: '24-bit/192kHz',
        playCount: 31,
        isFavorite: true,
        duration: '13:30',
        durationSeconds: 810,
      },
      {
        id: 'pft-4',
        rank: 4,
        title: 'Money',
        artist: 'Pink Floyd',
        album: 'The Dark Side of the Moon',
        dynamicRange: 'DR13',
        format: '24-bit/192kHz',
        playCount: 22,
        isFavorite: false,
        duration: '6:22',
        durationSeconds: 382,
      },
    ],
  },
  {
    id: 'art-2',
    name: 'Led Zeppelin',
    displayName: 'Led Zeppelin',
    genres: ['Hard Rock', 'Blues Rock', 'Heavy Metal'],
    albumCount: 9,
    trackCount: 86,
    totalDuration: '7h 18m',
    avatarUrl:
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
    bannerUrl:
      'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=1600&auto=format&fit=crop&q=80',
    featuredCoverUrl:
      'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&auto=format&fit=crop&q=80',
    bioSummary:
      'Formed in London in 1968, consisting of Robert Plant, Jimmy Page, John Paul Jones, and John Bonham. One of the best-selling and most influential rock groups.',
    losslessPlaytime: '48h Lossless',
    losslessPercentage: '100%',
    localStorageSize: '6.1 GB',
    discography: [
      {
        id: 'lz-1',
        title: 'Led Zeppelin IV',
        year: 1971,
        formatBadge: 'FLAC 24/96',
        coverUrl:
          'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&auto=format&fit=crop&q=80',
        trackCount: 8,
        isLocal: true,
        fileSize: '980 MB',
        releaseType: 'Studio Album',
        catalogNumber: 'SD-7208',
      },
      {
        id: 'lz-2',
        title: 'Led Zeppelin III',
        year: 1970,
        formatBadge: 'FLAC 24/96',
        coverUrl:
          'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&auto=format&fit=crop&q=80',
        trackCount: 10,
        isLocal: false,
        fileSize: '890 MB',
        releaseType: 'Studio Album',
        catalogNumber: 'SD-7201',
      },
      {
        id: 'lz-3',
        title: 'Physical Graffiti',
        year: 1975,
        formatBadge: 'FLAC 24/96',
        coverUrl:
          'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
        trackCount: 15,
        isLocal: false,
        fileSize: '1.85 GB',
        releaseType: 'Studio Album',
        catalogNumber: 'SS-2-200',
      },
      {
        id: 'lz-4',
        title: 'Led Zeppelin I',
        year: 1969,
        formatBadge: 'FLAC 24/96',
        coverUrl:
          'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
        trackCount: 9,
        isLocal: false,
        fileSize: '910 MB',
        releaseType: 'Studio Album',
        catalogNumber: 'SD-8216',
      },
      {
        id: 'lz-5',
        title: 'Led Zeppelin II',
        year: 1969,
        formatBadge: 'FLAC 24/96',
        coverUrl:
          'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=80',
        trackCount: 9,
        isLocal: false,
        fileSize: '940 MB',
        releaseType: 'Studio Album',
        catalogNumber: 'SD-8236',
      },
      {
        id: 'lz-6',
        title: 'Houses of the Holy',
        year: 1973,
        formatBadge: 'FLAC 24/96',
        coverUrl:
          'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=600&auto=format&fit=crop&q=80',
        trackCount: 8,
        isLocal: false,
        fileSize: '870 MB',
        releaseType: 'Studio Album',
        catalogNumber: 'SD-7255',
      },
    ],
    topTracks: [
      {
        id: 'lzt-1',
        rank: 1,
        title: 'Black Dog',
        artist: 'Led Zeppelin',
        album: 'Led Zeppelin IV',
        dynamicRange: 'DR14',
        format: '24-bit/96kHz',
        playCount: 41,
        isFavorite: true,
        duration: '4:56',
        durationSeconds: 296,
      },
      {
        id: 'lzt-2',
        rank: 2,
        title: 'Stairway to Heaven',
        artist: 'Led Zeppelin',
        album: 'Led Zeppelin IV',
        dynamicRange: 'DR12',
        format: '24-bit/96kHz',
        playCount: 38,
        isFavorite: true,
        duration: '8:02',
        durationSeconds: 482,
      },
    ],
  },
  {
    id: 'art-4',
    name: 'Miles Davis',
    displayName: 'Miles Davis',
    genres: ['Hard Bop', 'Modal Jazz', 'Jazz Fusion', 'Cool Jazz'],
    albumCount: 22,
    trackCount: 218,
    totalDuration: '24h 50m',
    avatarUrl:
      'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=80',
    bannerUrl:
      'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=1600&auto=format&fit=crop&q=80',
    featuredCoverUrl:
      'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=80',
    bioSummary:
      'Among the most influential and acclaimed figures in the history of jazz and 20th-century music, spearheading modal jazz, cool jazz, and jazz-rock fusion.',
    losslessPlaytime: '98h Lossless',
    losslessPercentage: '100%',
    localStorageSize: '16.8 GB',
    discography: [
      {
        id: 'md-1',
        title: 'Kind of Blue',
        year: 1959,
        formatBadge: 'DSD256',
        coverUrl:
          'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=80',
        trackCount: 5,
        isLocal: true,
        fileSize: '2.10 GB',
        releaseType: 'Studio Album',
        catalogNumber: 'CL-1355',
      },
      {
        id: 'md-2',
        title: 'Bitches Brew',
        year: 1970,
        formatBadge: 'FLAC 24/192',
        coverUrl:
          'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=600&auto=format&fit=crop&q=80',
        trackCount: 6,
        isLocal: true,
        fileSize: '1.95 GB',
        releaseType: 'Studio Album',
        catalogNumber: 'GP-26',
      },
      {
        id: 'md-3',
        title: 'In a Silent Way',
        year: 1969,
        formatBadge: 'FLAC 24/192',
        coverUrl:
          'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
        trackCount: 2,
        isLocal: false,
        fileSize: '890 MB',
        releaseType: 'Studio Album',
        catalogNumber: 'CS-9875',
      },
      {
        id: 'md-4',
        title: 'Sketches of Spain',
        year: 1960,
        formatBadge: 'DSD128',
        coverUrl:
          'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&auto=format&fit=crop&q=80',
        trackCount: 5,
        isLocal: false,
        fileSize: '1.30 GB',
        releaseType: 'Studio Album',
        catalogNumber: 'CL-1480',
      },
      {
        id: 'md-5',
        title: 'Round About Midnight',
        year: 1957,
        formatBadge: 'FLAC 24/96',
        coverUrl:
          'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
        trackCount: 6,
        isLocal: false,
        fileSize: '760 MB',
        releaseType: 'Studio Album',
        catalogNumber: 'CL-949',
      },
    ],
    topTracks: [
      {
        id: 'mdt-1',
        rank: 1,
        title: 'So What',
        artist: 'Miles Davis',
        album: 'Kind of Blue',
        dynamicRange: 'DR15',
        format: 'DSD256',
        playCount: 54,
        isFavorite: true,
        duration: '9:22',
        durationSeconds: 562,
      },
    ],
  },
  {
    id: 'art-5',
    name: 'John Coltrane',
    displayName: 'John Coltrane',
    genres: ['Hard Bop', 'Modal Jazz', 'Free Jazz'],
    albumCount: 14,
    trackCount: 94,
    totalDuration: '11h 15m',
    avatarUrl:
      'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=600&auto=format&fit=crop&q=80',
    bannerUrl:
      'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=1600&auto=format&fit=crop&q=80',
    featuredCoverUrl:
      'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=600&auto=format&fit=crop&q=80',
    bioSummary: 'American jazz saxophonist and composer whose work shaped post-bop and free jazz.',
    losslessPlaytime: '56h Lossless',
    losslessPercentage: '100%',
    localStorageSize: '7.2 GB',
    discography: [
      {
        id: 'jc-1',
        title: 'A Love Supreme',
        year: 1965,
        formatBadge: 'FLAC 24/192',
        coverUrl:
          'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=600&auto=format&fit=crop&q=80',
        trackCount: 4,
        isLocal: true,
        fileSize: '1.20 GB',
        releaseType: 'Studio Album',
        catalogNumber: 'AS-77',
      },
      {
        id: 'jc-2',
        title: 'Giant Steps',
        year: 1960,
        formatBadge: 'FLAC 24/192',
        coverUrl:
          'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=80',
        trackCount: 7,
        isLocal: false,
        fileSize: '1.15 GB',
        releaseType: 'Studio Album',
        catalogNumber: 'SD-1311',
      },
      {
        id: 'jc-3',
        title: 'Blue Train',
        year: 1957,
        formatBadge: 'DSD128',
        coverUrl:
          'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
        trackCount: 5,
        isLocal: false,
        fileSize: '1.45 GB',
        releaseType: 'Studio Album',
        catalogNumber: 'BLP-1577',
      },
      {
        id: 'jc-4',
        title: 'My Favorite Things',
        year: 1961,
        formatBadge: 'FLAC 24/96',
        coverUrl:
          'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&auto=format&fit=crop&q=80',
        trackCount: 4,
        isLocal: false,
        fileSize: '980 MB',
        releaseType: 'Studio Album',
        catalogNumber: 'SD-1361',
      },
    ],
  },
  {
    id: 'art-6',
    name: 'Herbie Hancock',
    displayName: 'Herbie Hancock',
    genres: ['Post-Bop', 'Jazz-Funk', 'Fusion'],
    albumCount: 12,
    trackCount: 82,
    totalDuration: '9h 30m',
    avatarUrl:
      'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
    bannerUrl:
      'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1600&auto=format&fit=crop&q=80',
    featuredCoverUrl:
      'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
    bioSummary:
      "Iconic keyboardist and composer who helped define the post-bop rhythm section in Miles Davis' Second Great Quintet.",
    losslessPlaytime: '34h Lossless',
    losslessPercentage: '100%',
    localStorageSize: '5.9 GB',
    discography: [
      {
        id: 'hh-1',
        title: 'Head Hunters',
        year: 1973,
        formatBadge: 'FLAC 24/192',
        coverUrl:
          'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=600&auto=format&fit=crop&q=80',
        trackCount: 4,
        isLocal: true,
        fileSize: '1.35 GB',
        releaseType: 'Studio Album',
        catalogNumber: 'KC-32731',
      },
      {
        id: 'hh-2',
        title: 'Maiden Voyage',
        year: 1965,
        formatBadge: 'DSD128',
        coverUrl:
          'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
        trackCount: 5,
        isLocal: false,
        fileSize: '1.28 GB',
        releaseType: 'Studio Album',
        catalogNumber: 'BST-84195',
      },
      {
        id: 'hh-3',
        title: "Takin' Off",
        year: 1962,
        formatBadge: 'FLAC 24/96',
        coverUrl:
          'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=80',
        trackCount: 6,
        isLocal: false,
        fileSize: '820 MB',
        releaseType: 'Studio Album',
        catalogNumber: 'BST-84109',
      },
      {
        id: 'hh-4',
        title: 'Thrust',
        year: 1974,
        formatBadge: 'FLAC 24/96',
        coverUrl:
          'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
        trackCount: 4,
        isLocal: false,
        fileSize: '890 MB',
        releaseType: 'Studio Album',
        catalogNumber: 'PC-32965',
      },
    ],
  },
];

export const DEMO_ALBUMS: AlbumItem[] = [
  {
    id: 'alb-4',
    title: 'Cowboy Bebop (Original Soundtrack 1)',
    artist: 'The Seatbelts',
    year: 1998,
    trackCount: 22,
    totalDuration: '62:15',
    format: 'FLAC 24/192',
    codec: 'FLAC',
    catalogNumber: 'VICL-60201',
    dynamicRange: 'DR15',
    genre: 'Big Band Jazz / Blues / Bebop',
    label: 'Victor Entertainment / FlyingDog',
    fileSize: '1.82 GB',
    sampleRate: '192 kHz',
    bitDepth: '24-bit',
    replayGain: '-1.8 dB',
    losslessPercentage: '100%',
    description:
      'The definitive debut original soundtrack for Cowboy Bebop composed by Yoko Kanno and recorded by The Seatbelts. Featuring explosive hard-bop big band horn charts, soulful harmonica blues, and pristine studio separation.',
    coverUrl:
      'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=600&auto=format&fit=crop&q=80',
    bannerUrl:
      'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=1600&auto=format&fit=crop&q=80',
    tracks: DEMO_TRACKS.filter((t) => t.album.includes('Cowboy Bebop')),
  },
  {
    id: 'alb-1',
    title: 'Wish You Were Here',
    artist: 'Pink Floyd',
    year: 1975,
    trackCount: 5,
    totalDuration: '44:28',
    format: 'FLAC 24/192',
    codec: 'FLAC',
    catalogNumber: 'PC-33453',
    dynamicRange: 'DR15',
    genre: 'Progressive Rock / Art Rock',
    label: 'Harvest / Columbia Records',
    fileSize: '1.45 GB',
    sampleRate: '192 kHz',
    bitDepth: '24-bit',
    replayGain: '-2.4 dB',
    losslessPercentage: '100%',
    description:
      'Recorded at Abbey Road Studios, Pink Floyd’s ninth studio album explores themes of absence, the music business alienation, and former bandmate Syd Barrett. Sourced from original analog studio master tapes.',
    coverUrl:
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
    bannerUrl:
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=1600&auto=format&fit=crop&q=80',
    tracks: DEMO_TRACKS.slice(0, 5),
  },
  {
    id: 'alb-2',
    title: 'The Dark Side of the Moon',
    artist: 'Pink Floyd',
    year: 1973,
    trackCount: 10,
    totalDuration: '42:50',
    format: 'FLAC 24/192',
    codec: 'FLAC',
    catalogNumber: 'SHVL-804',
    dynamicRange: 'DR14',
    genre: 'Progressive Rock / Psychedelic',
    label: 'Harvest Records',
    fileSize: '1.38 GB',
    sampleRate: '192 kHz',
    bitDepth: '24-bit',
    replayGain: '-3.1 dB',
    losslessPercentage: '100%',
    description:
      'An enduring masterpiece engineered by Alan Parsons featuring pioneering quadraphonic mixdowns, VCS3 synthesizers, and pristine studio clock sound effects.',
    coverUrl:
      'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=600&auto=format&fit=crop&q=80',
    bannerUrl:
      'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=1600&auto=format&fit=crop&q=80',
    tracks: DEMO_TRACKS.slice(5, 7),
  },
  {
    id: 'alb-3',
    title: 'Led Zeppelin IV',
    artist: 'Led Zeppelin',
    year: 1971,
    trackCount: 8,
    totalDuration: '42:34',
    format: 'FLAC 24/96',
    codec: 'FLAC',
    catalogNumber: 'SD-7208',
    dynamicRange: 'DR14',
    genre: 'Hard Rock / Blues Rock / Folk Rock',
    label: 'Atlantic Records',
    fileSize: '980 MB',
    sampleRate: '96 kHz',
    bitDepth: '24-bit',
    replayGain: '-1.5 dB',
    losslessPercentage: '100%',
    description:
      'Recorded at Headley Grange using the Rolling Stones Mobile Studio. Captures the iconic drum reverberation of John Bonham and Jimmy Page’s multi-layered acoustic and electric guitar tapestries.',
    coverUrl:
      'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=600&auto=format&fit=crop&q=80',
    bannerUrl:
      'https://images.unsplash.com/photo-1511192336575-5a79af67a629?w=1600&auto=format&fit=crop&q=80',
    tracks: DEMO_TRACKS.slice(7, 10),
  },
  {
    id: 'alb-5',
    title: 'Kind of Blue',
    artist: 'Miles Davis',
    year: 1959,
    trackCount: 5,
    totalDuration: '45:44',
    format: 'DSD256',
    codec: 'DSD64',
    catalogNumber: 'CS-8163',
    dynamicRange: 'DR15',
    genre: 'Modal Jazz / Hard Bop',
    label: 'Columbia Records',
    fileSize: '3.12 GB',
    sampleRate: '11.2 MHz (DSD256)',
    bitDepth: '1-bit DSD',
    replayGain: '-4.6 dB',
    losslessPercentage: '100%',
    description:
      'The pinnacle of modal jazz improvisation featuring John Coltrane, Cannonball Adderley, Bill Evans, Paul Chambers, and Jimmy Cobb. Remastered directly from the 3-track session tapes.',
    coverUrl:
      'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=600&auto=format&fit=crop&q=80',
    bannerUrl:
      'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?w=1600&auto=format&fit=crop&q=80',
    tracks: DEMO_TRACKS.slice(15, 17),
  },
];

export const LOCAL_TRACKS: TrackItem[] = isDemoMode ? DEMO_TRACKS : [];
export const LOCAL_ARTISTS: ArtistItem[] = isDemoMode ? DEMO_ARTISTS : [];
export const LOCAL_ALBUMS: AlbumItem[] = isDemoMode ? DEMO_ALBUMS : [];
